version: "3"
services:
  solr:
    container_name: solr
    image: 9311561018/onecdp-solr:8.11.4
    ports:
      - 8983:8983
    volumes:
      - ./data/solr:/var/data/solr
  postgresql:
    container_name: postgresql
    image: postgres:13
    environment:
      #- POSTGRES_PASSWORD=dSMghXDW6B
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/data/postgresql