apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          #ports:
          #  - containerPort: 9094
          env:
            - name: KAFKA_CFG_NODE_ID
              value: '0'
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              #value: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
              value: PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@localhost:9093
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            #- name: REPLICAS
            #  value: '3'
            #- name: SERVICE
            #  value: kafka-svc
            #- name: NAMESPACE
            #  value: kafka
            #- name: SHARE_DIR
            #  value: /mnt/kafka
            #- name: CLUSTER_ID
            #  value: bXktY2x1c3Rlci0xMjM0NQ==
            #- name: DEFAULT_REPLICATION_FACTOR
            #  value: '3'
            #- name: DEFAULT_MIN_INSYNC_REPLICAS
            #  value: '2'
          #volumeMounts:
          #  - name: data
          #    mountPath: /mnt/kafka
  #volumeClaimTemplates:
  #  - metadata:
  #      name: data
  #    spec:
  #      accessModes:
  #        - "ReadWriteOnce"
  #      resources:
  #        requests:
  #          storage: "1Gi"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-svc
#  namespace: kafka
#  labels:
#    app: kafka-app
#spec:
#  type: NodePort
#  ports:
#    - name: '9094'
#      port: 9094
#      protocol: TCP
#      targetPort: 9094
#      nodePort: 30092
#  selector:
#    app: kafka-app
#---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: kafka
spec:
  ports:
    # Accept traffic sent to port 
    - name: tcp
      port: 9092
      targetPort: 9092
  selector:
    # this label selector
    app: kafka
  type: ClusterIP