apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  namespace: default
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
        - name: solr
          image: 9311561018/onecdp-solr:8.11.4
          env:
            - name: SOLR_XMX
              value: 1024m
---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: solr-svc
spec:
  ports:
    # Accept traffic sent to port 
    - name: tcp8983
      port: 8983
      targetPort: 8983
  selector:
    # this label selector
    app: solr
  type: ClusterIP