apiVersion: v1
kind: Ingress
metadata:
  namespace: default
  name: cdp-data-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: cdp-data-api-ingress
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cdp-data-api
            port:
              number: 80